/**
 * 本文から meta description を組み立てる規則。
 *
 * もとは remark-archive-description.ts の中にあった。Notion 記事でも
 * 同じ規則を使うことになったので切り出した。
 * 「どの構文木から段落テキストを取り出すか」は呼び出し側の仕事で、
 * 「取り出したテキストからどう説明文を作るか」だけをここが持つ。
 *
 * 入口が 2 つになった以上、規則が片方だけ変わると
 * アーカイブと Notion で説明文の作り方がずれる。1 箇所にまとめておく。
 */

// 日本語の検索結果で表示される目安。全角で 110 文字あれば
// 大半は途中で切れずに収まる。超える分は末尾を … にする。
//
// なお Google のスニペットは文字数ではなく表示幅で打ち切られ、
// 日本語だと全角 40〜55 文字程度しか出ない。110 は「渡す材料」として
// 多めに持たせている値で、実際に効くのは先頭 40〜50 文字
export const MAX_LENGTH = 110

// これより短い段落は前置き（「どうも。」など）とみなして読み飛ばす。
// ただし本文がそれしか無い場合に備えて、拾えたものは捨てない
const MIN_PARAGRAPH = 10

/**
 * 写真キャプションか。
 *
 * 移行元では写真の前後に機材名・撮影者・EXIF が «素のテキスト段落» で
 * 入っている。リンクでも画像でもないので普通の段落として拾われ、
 * 10 文字も優に超えるため、そのまま description の先頭を占領していた。
 * 実測 16 記事が「SONY α7R SONY SEL55F18Z photo by mizuka123 …」の
 * ような EXIF だけの説明文になり、うち 6 記事は撮影時刻と絞りしか
 * 違わない実質重複だった。
 *
 * 判定は «仮名を含むか» を軸にする。日本語の地の文には必ず仮名が入るが、
 * 機材名（SONY α7R / CANON EF24-70mm F2.8L II USM）、撮影者
 * （photo by mizuka123）、EXIF 行（2014:10:04 12:52:54撮影 …）には
 * 仮名が無い（撮影は漢字なので漢字は判定に使えない）。
 */
export const isCaption = (text: string): boolean => {
  if (/photo by |generated by /i.test(text)) return true
  return !/[ぁ-んァ-ヶ]/.test(text)
}

/**
 * 全角・半角をまたぐ絵文字などでサロゲートペアが割れないよう、
 * コードポイント単位で切る。
 */
export const truncate = (text: string): string => {
  const chars = [...text]
  return chars.length <= MAX_LENGTH
    ? text
    : `${chars.slice(0, MAX_LENGTH).join('')}…`
}

/** 空白を潰して 1 行にする。 */
export const normalize = (text: string): string =>
  text.replace(/\s+/g, ' ').trim()

const pick = (paragraphs: string[], skipCaption: boolean): string[] => {
  const parts: string[] = []

  for (const paragraph of paragraphs) {
    const text = normalize(paragraph)
    if (!text) continue
    if (skipCaption && isCaption(text)) continue
    if (text.length < MIN_PARAGRAPH && parts.length === 0) continue

    parts.push(text)
    if (parts.join(' ').length >= MAX_LENGTH) break
  }

  return parts
}

/**
 * 段落テキストの配列から説明文を作る。作れなければ空文字。
 *
 * 呼び出し側は「本文の段落を文書順に並べた配列」を渡すこと。
 * 画像・コード・生 HTML・商品ボックスの除外は呼び出し側の責任。
 */
export const buildDescription = (paragraphs: string[]): string => {
  // まず地の文だけで組む。1 つも拾えなければ（写真だけの記事や
  // 英語だけの記事）キャプション判定を外して拾い直す。
  // 説明文が空になって共通説明に落ちるより、EXIF でも何か出す方がよい
  const parts = pick(paragraphs, true)
  const fallback = parts.length > 0 ? parts : pick(paragraphs, false)

  return truncate(fallback.join(' ').trim())
}
